name: "mnist"

data_dir: ${data_dir} # data_dir is specified in config.yaml
batch_size: 64
test_batch_size: 500
num_workers: 1
num_train_samples: 0
targets: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] #conditional in command line [[0,1],[1,7],[4,5]]
